services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8081:80"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    env_file:
      - .frontend.env
    networks:
      - purple-net
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ../backend:/app
      - /app/node_modules
    env_file:
      - .backend.env
    networks:
      - purple-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    env_file:
      - .db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6432:5432"
    networks:
      - purple-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U music -d purple"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  purple-net:
    driver: bridge

volumes:
  pgdata: